// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycby6KCGHVMQp6hSbR7uSl6eB_4cPSyD99pmYIBOx2RysWm3_Pf_aNIBFRK2MyB2rzXInQg/exec";
